# Generated by Django 5.0.3 on 2024-04-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgobullsDivision',
            fields=[
                ('division_name', models.TextField(db_column='Division Name', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Algobulls Division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlgobullsEmployee',
            fields=[
                ('employee_id', models.BigIntegerField(db_column='Employee ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_collation='C', db_column='Name', null=True)),
                ('email_id', models.TextField(blank=True, db_column='Email ID', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
            ],
            options={
                'db_table': 'Algobulls Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.BigIntegerField(db_column='Branch ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('broker_id', models.BigIntegerField(db_column='Broker ID', primary_key=True, serialize=False)),
                ('broker_name', models.TextField(blank=True, db_collation='C', db_column='Broker Name', null=True)),
            ],
            options={
                'db_table': 'Brokers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerSideEmployee',
            fields=[
                ('employee_id', models.BigIntegerField(db_column='Employee ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('email_id', models.TextField(blank=True, db_column='Email ID', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
            ],
            options={
                'db_table': 'Broker Side Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('history_id', models.BigIntegerField(db_column='History ID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('assigned_to', models.TextField(blank=True, db_column='Assigned To', null=True)),
                ('changed_by', models.TextField(blank=True, db_column='Changed By', null=True)),
            ],
            options={
                'db_table': 'Issue History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issue_id', models.BigIntegerField(db_column='Issue ID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('name', models.TextField(blank=True, db_collation='C', db_column='Name', null=True)),
                ('contact_number', models.BigIntegerField(blank=True, db_column='Contact Number', null=True)),
                ('broking_id', models.BigIntegerField(blank=True, db_column='Broking ID', null=True)),
                ('email_id', models.TextField(blank=True, db_column='Email ID', null=True)),
                ('strategy_code', models.BigIntegerField(blank=True, db_column='Strategy Code', null=True)),
                ('strategy_instrument', models.TextField(blank=True, db_column='Strategy Instrument', null=True)),
                ('customer_type', models.TextField(blank=True, db_column='Customer Type', null=True)),
                ('priority', models.TextField(blank=True, db_column='Priority', null=True)),
                ('issue', models.TextField(blank=True, db_column='Issue', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('date_of_closing', models.DateField(blank=True, db_column='Date of closing', null=True)),
            ],
            options={
                'db_table': 'Issues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.BigIntegerField(db_column='Permission ID', primary_key=True, serialize=False)),
                ('permission_name', models.TextField(blank=True, db_column='Permission Name', null=True)),
            ],
            options={
                'db_table': 'Permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionAccessTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Permission Access Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.BigIntegerField(db_column='Role ID', primary_key=True, serialize=False)),
                ('role_name', models.TextField(blank=True, db_column='Role Name', null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLeads',
            fields=[
                ('lead_id', models.BigIntegerField(db_column='Lead ID', primary_key=True, serialize=False)),
                ('broking_id', models.BigIntegerField(blank=True, db_column='Broking ID', null=True)),
                ('name', models.TextField(blank=True, db_collation='C', db_column='Name', null=True)),
                ('contact_number', models.BigIntegerField(blank=True, db_column='Contact Number', null=True)),
                ('email_id', models.TextField(blank=True, db_column='Email ID', null=True)),
                ('source_type', models.TextField(blank=True, db_column='Source Type', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('risk_appetite', models.TextField(blank=True, db_column='Risk Appetite', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('amount', models.BigIntegerField(blank=True, db_column='Amount', null=True)),
                ('purchase_date', models.DateField(blank=True, db_column='Purchase Date', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('reason_for_dropped', models.TextField(blank=True, db_column='Reason For Dropped', null=True)),
            ],
            options={
                'db_table': 'Sales Leads',
                'managed': False,
            },
        ),
    ]
