# Generated by Django 5.0.3 on 2024-04-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuehistory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'managed': True},
        ),
    ]
