# Generated by Django 5.0.3 on 2024-04-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_issuehistory_options_alter_issues_options'),
    ]

    operations = [
        
    ]
