# Generated by Django 5.0.3 on 2024-04-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_issuehistory_issue_id_issues_branch_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algobullsdivision',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='algobullsemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='brokers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='brokersideemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permissionaccesstable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salesleads',
            options={'managed': True},
        ),
    ]
