# Generated by Django 5.0.3 on 2024-04-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_algobullsdivision_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuehistory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='brokers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='brokersideemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permissionaccesstable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salesleads',
            options={'managed': True},
        ),
    ]
