# Generated by Django 5.0.3 on 2024-04-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_algobullsdivision_options_and_more'),
    ]

    operations = [
        
    ]
