# Generated by Django 5.0.3 on 2024-04-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_issuehistory_issue_id_issues_branch_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuehistory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'managed': True},
        ),
    ]
    