# Generated by Django 5.0.3 on 2024-04-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_issuehistory_issue_id_issues_branch_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algobullsdivision',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='algobullsemployee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='brokers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='brokersideemployee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permissionaccesstable',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salesleads',
            options={'managed': False},
        ),
    ]
