# Generated by Django 5.0.3 on 2024-04-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_algobullsdivision_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algobullsdivision',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='algobullsemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='brokers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='brokersideemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permissionaccesstable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salesleads',
            options={'managed': True},
        ),
    ]
