# Generated by Django 5.0.3 on 2024-04-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_algobullsdivision_options_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='salesleads',
            name='status',
            field=models.TextField(blank=True, choices=[('Done', 'Done'), ('ND', 'Not Done')], db_column='Status', null=True),
        ),
    ]
