# Generated by Django 5.0.3 on 2024-04-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_salesleads_options_algobullsdivision_head_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesleads',
            options={'managed': True, 'permissions': [('edit_lead_id', 'Can edit the Lead ID field of Sales Leads'), ('edit_branch_employee_id', 'Can edit the Branch Employee ID field of Sales Leads'), ('edit_sales_employee_id', 'Can edit the Sales Employee ID field of Sales Leads'), ('edit_broking_id', 'Can edit the Broking ID field of Sales Leads'), ('edit_name', 'Can edit the Name field of Sales Leads'), ('edit_contact_number', 'Can edit the Contact Number field of Sales Leads'), ('edit_email_id', 'Can edit the Email ID field of Sales Leads'), ('edit_source_type', 'Can edit the Source Type field of Sales Leads'), ('edit_category', 'Can edit the Category field of Sales Leads'), ('edit_risk_appetite', 'Can edit the Risk Appetite field of Sales Leads'), ('edit_comments', 'Can edit the Comments field of Sales Leads'), ('edit_amount', 'Can edit the Amount field of Sales Leads'), ('edit_purchase_date', 'Can edit the Purchase Date field of Sales Leads'), ('edit_status', 'Can edit the Status field of Sales Leads'), ('edit_reason_for_dropped', 'Can edit the Reason For Dropped field of Sales Leads')]},
        ),
        
    ]
