# Generated by Django 5.0.3 on 2024-04-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_salesleads_options_algobullsdivision_head_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesleads',
            options={'managed': True},
        ),
        
    ]
